name : Blog of Endle
title : Blog of Endle
description: Fedora/Firefox/Wine User. 一日萌新 一生萌新


# For more see: https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:year/:month/:day/:title/ 

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
lsi: false
highlighter: rouge
paginate: 5 
# GitHub Pages only supports kramdown as a Markdown processor.
markdown: kramdown

plugins: [jekyll-paginate, rouge, kramdown]

baseurl: ''


# This can be '' to hide the Github nav button
github: ''

comments: true
disqus: 'endle'
  
# For sitemap
production_url: 'https://blog.zhenbo.pro' 

